### ISSUE TITLE
Photoshop CC Issue

### ISSUE THREAD

**Issue by DevAgency** [iamdarrenhall/list-fonts#4]
Hi,

After the copy/paste of List Fonts.jsx, i have close and reopen photoshop, i tried to use the script but something happen.
See attachment.

Thanks for your help

![capture d ecran 2015-03-31 a 22 31 56](https://cloud.githubusercontent.com/assets/10207342/6928731/7350e696-d7f6-11e4-9c6d-97a9a5de1c0b.png)

**Comment by iamdarrenhall** [comment]
Hi, does it happen in just the one file, or in multiple files?

**Comment by DevAgency** [comment]
Hi, Thanks for your fast answer.

In multiple files, i just tried.

**Comment by iamdarrenhall** [comment]
It looks like you've saved the file incorrectly. [Download the repository](https://github.com/iamdarrenhall/list-fonts/archive/master.zip) and copy the `List Fonts.jsx` file from there.

**Comment by DevAgency** [comment]
You was right! Thanks!
